### ISSUE TITLE
problem with path on windows

### ISSUE THREAD

**Issue by antoniopuero** [javoire/browserify-ng-html2js#10]
Hi,

there is a problem with back slashes in template path on windows when baseDir is set. (That's caused by path.join method).

Porbably you have some ideas how to handle it, thank in advance

**Comment by javoire** [comment]
Aha,

So you set e.g. `baseDir: "path\on\windows"` and then [this line](https://github.com/javoire/browserify-ng-html2js/blob/master/lib/index.js#L39) is run
```js
fileName = opts.baseDir ? file.replace(path.join(appDir, opts.baseDir), '') : file.match(fileMatching)[1];
```
that joins the `baseDir` and the `appDir `. (`path.join(appDir, opts.baseDir)´). 

What's the output of that? Do you get some sort of output in the browser console or terminal?

**Comment by antoniopuero** [comment]
The name in template cache is set with back slashes. So ```file.replace(path.join(appDir, opts.baseDir), '') .replace(/\\/g, '/')``` works fine for me

**Comment by javoire** [comment]
Are you using backslashes for `baseDir`?

**Comment by antoniopuero** [comment]
nope, path module takes care of it. The problem is that it returns windows-like path instead of unix-like. so ```/src/app/some-directive.html``` doesn't match ```\src\app\some-directive.html```

**Comment by javoire** [comment]
Ahh I see, the template cache needs to have unix-like paths `/src/app/some-directive.html` but instead it's given `\src\app\some-directive.html` (due to the path.join operation) which won't work for angulars template cache?

So `file.replace(path.join(appDir, opts.baseDir), '') .replace(/\\/g, '/')` fixes that I see. Would you like to do a PR for that?

**Comment by antoniopuero** [comment]
heh, of course :)

**Comment by javoire** [comment]
#12
