### ISSUE TITLE
Passing parameters via package.json

### ISSUE THREAD

**Issue by mparpaillon** [javoire/browserify-ng-html2js#16]
Hi, I'm trying to pass the "module" as parameter on the package.json but I can't find the proper syntax.
How would you do that ?

Thanks

**Comment by mparpaillon** [comment]
Ok, I've finally managed to do it like this:

```
{
  "name": "Blah",
  "version": "1.0.0",
  "devDependencies": {
    "browserify-ng-html2js": "^1.1.0"
  },
  "browserify": {
    "transform": [
      [ "browserify-ng-html2js", { "module": "ngPartials" } ]
    ]
  }
}
```

So hard to find the correct syntax in Browserify documentation... awful
Anyway, hope it helps someone

**Comment by javoire** [comment]
Aha, I guess we should add this to the readme

**Comment by felixbillon** [comment]
+1
