### ISSUE TITLE
1.1.1 breaks Angular versions that don't support commonjs

### ISSUE THREAD

**Issue by teddyhwang** [javoire/browserify-ng-html2js#18]
The latest release and this [commit](https://github.com/javoire/browserify-ng-html2js/commit/6777bb269d5d085904a8d633a8924543147fee94) breaks any version of Angular JS that does not support commonjs. This includes all 1.2.x versions of Angular and any version < Angular 1.3.14 (1.3.14 is when they introduced commonjs support).

**Comment by javoire** [comment]
Hmm tricky. @cgmartin, do you have any ideas on this?

Version 1.1.1 better supports isolated unit testing, but breaks apps that have older versions of angular (non CommonJS supported)

Maybe theres a way to introduce a conditional in the mix here, to support both cases

**Comment by cgmartin** [comment]
@javoire Ah shoot, didn't consider that as a breaking change. Your idea for a conditional seems best. An option to enable the `require('angular');` line. By default, it would be disabled and the rendered output would be as before the commit.

I can make an attempt at a PR fix tonight/tomorrow if no one beats me to it.

**Comment by javoire** [comment]
e6b7ee39d8ebbc42523e713d40dec08226465e56
