### ISSUE TITLE
Error: [$compile:tpload] Failed to load template: <<already seen>>

### ISSUE THREAD

**Issue by elijahwww** [javoire/browserify-ng-html2js#21]
I am getting an error which looks like templateUrl value is being interpreted as object and not string, then goes out and fails at GET http://..object.
What am i doing wrong?

my code simply:
```
var angular = require('angular');
var app = angular.module('helloApp', []);
app.directive('test1',  function (){
	return {
		templateUrl: require('../templates/test.html')
	};
});
```

`GET http://localhost:3000/[object%20Object] 404 (Not Found)`
```
Error: [$compile:tpload] Failed to load template: {"_configBlocks":[],"_runBlocks":[["$templateCache",null]],"requires":[],"name":"test.html","requiresOriginal":"<<already seen>>"}
```
transpiled code:
```
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
(function (global){
'use strict';
var angular = (typeof window !== "undefined" ? window.angular : typeof global !== "undefined" ? global.angular : null);
var app = angular.module('helloApp', []);
app.directive('test1',  function (){
	return {
		templateUrl: require('../templates/test.html')
	};
});


}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})

},{"../templates/test.html":2}],2:[function(require,module,exports){
var ngModule = angular.module('test.html', []);
ngModule.run(['$templateCache', function($templateCache) {
  $templateCache.put('test.html',
    '<div>template 1</div>\n' +
    '');
}]);

module.exports = ngModule;
},{}]},{},[1])
```

**Comment by javoire** [comment]
well the `require('../templates/test.html')` is returning a module (object). `templateUrl:` expects a string

try `templateUrl: require('../templates/test.html').name`

your `templateUrl` should be the same string as `test.html` (`var ngModule = angular.module('test.html', []);`)

**Comment by javoire** [comment]
any luck? :)

**Comment by panzerdp** [comment]
Unfortunately I have the same problem.
Using `require('test.html').name` doesn't solve the problem.
Thanks.

**Comment by javoire** [comment]
This should be one way of doing it.

```js
// app.js

var angular = require('angular');

var app = angular.module('helloApp', [
  require('../templates/test.html').name
]);

app.directive('test1',  function (){
    return {
        templateUrl: '../templates/test.html'
    };
});
```

templateUrl takes a string, not an object. browserify-ng-html2js takes care of putting the html template into angular template cache. so when the directive above is looking for the template, it'll grab it from the template cache.

Study the tests to see different way of using browserify-ng-html2js https://github.com/javoire/browserify-ng-html2js/tree/master/test

**Comment by elijahwww** [comment]
Hi, sorry it took me a while to get back to this. It does work when calling `require('my-template.html')` either in parent module definition: `angular.module('helloApp', ['templates', require('../templates/test.html').name]);` or just somewhere before the module is defined. 
```
require('../templates/test.html');
var app = angular.module('helloApp', ['templates']);
```
Thanks for writing this transformer!!!

**Comment by javoire** [comment]
Great to hear! Yes, browserify just needs to first load the actual template code with `require('template.html')` and then the template is referenced to by its name in eg a directive:  `templateUrl: "template.html"`. (depending on you configurations.. ). Closing this now :)
