### ISSUE TITLE
Require templates into app

### ISSUE THREAD

**Issue by mchambaud** [javoire/browserify-ng-html2js#29]
Hey, is it possible to require the generated module in the application?

```
   angular.module('app', [
       require('angular-cookies'),
       require('angular-animate'),
       require('angular-ui-router'),
       'templates'
   ]);
```

**Comment by javoire** [comment]
Yes, just pass the name you specify in the `module: 'templates'` option
https://github.com/javoire/browserify-ng-html2js#b-with-gulp

**Comment by mchambaud** [comment]
What I meant is to be able to this:

```
   angular.module('app', [
       require('angular-cookies'),
       require('angular-animate'),
       require('angular-ui-router'),
       require('templates')
   ]);
```

**Comment by vendethiel** [comment]
@javoire Is there a way to configure this using browserify's `-t` syntax, though? I can't seem to find anything about it.

**Comment by javoire** [comment]
@mchambaud correct me if I'm wrong (which I might be) but aren't you supposed to do 

```js
 angular.module('app', [
       require('angular-cookies').name,
       require('angular-animate').name,
       require('angular-ui-router').name,
       require('templates').name
   ]);
```

which will be intepreted as

 angular.module('app', [
       'ngCookies',
       'ngAnimate',
       'uiRouter',
       'templates'
   ]);
```
(with reservation for the module names not being correct because I'm guessing what they're called :)

**Comment by mchambaud** [comment]
module.exports should export the name, no need to add ".name". 

In any case, neither require('templates') or requires('templates').name work.

**Comment by javoire** [comment]
the reason this
```js
angular.module('app', [
       require('angular-cookies'),
       require('angular-animate'),
       require('angular-ui-router'),
       require('templates') // <-----
   ]);
```
won't work is that you need to require a _filepath_ in your own source. `require('angular-ui-router')` works because there's an NPM module with that name in your `node_modules` folder. An NPM module requires a package.json file for it to be found by `require`. Like so
https://github.com/angular-ui/ui-router/blob/e2bdf86a3fbd7369bdd59d9d77fc5fc956f0a7dc/package.json#L2

Which also points to the main entrypoint of the module:
https://github.com/angular-ui/ui-router/blob/e2bdf86a3fbd7369bdd59d9d77fc5fc956f0a7dc/package.json#L86

Therefore you need to do
```js
angular.module('app', [
       require('angular-cookies'),
       require('angular-animate'),
       require('angular-ui-router'),
       require('myTemplate.html') // <-----
   ]);
```

Unless you use the `module: 'allMyTemplates'` option (https://github.com/javoire/browserify-ng-html2js#b-with-gulp). In which case you can do

```js
angular.module('app', [
       require('angular-cookies'),
       require('angular-animate'),
       require('angular-ui-router'),
      'allMyTemplates'
   ]);
```

Since it puts all your templates in the same angular module.

Does this make sense? :)

**Comment by vendethiel** [comment]
That won't work still (in my experience), because since the templates aren't required, they will not be added to the build by browserify. I had to use `require('bulk-require')(__dirname, ['./templates/*.html'])` for browserify to pick them up.

**Comment by javoire** [comment]
So the main concept here is that `require` is browserifys module loader, and `angular.module('app', ['someModule'] );` is angular module loader.

So basically what you always have to do is
```js
require('angular-cookies');
require('angular-animate');
require('angular-ui-router');
require('./templates/home.html');
require('./templates/footer.html');

angular.module('app', [
  'anguar-cookies',
  'angular-animate',
  'angular-ui-router',
  'templates'
]);
```

First you tell browserify to pick up the module in it's pipeline, and then you tell angular to load the modules, now that they're included in the bundle.

@vendethiel yes exactly :) bulk requiring them seems like a nice way to throw all of the html templates into browserify at once yeah

**Comment by javoire** [comment]
With the latest update you should be able to do

```js
// for browserify
require('angular-cookies');
require('angular-animate');
require('angular-ui-router');

// for angular
angular.module('app', [
  'ngCookies',
  'ngAnimate',
  'ui.router',
  require('./templates/home.html');
  require('./templates/footer.html');
]);
```
Though since the template modules are exporting their module names
https://github.com/javoire/browserify-ng-html2js/pull/31

**Comment by vendethiel** [comment]
well, with `,` instead of `;` for these requires.

**Comment by javoire** [comment]
thx, updated :)

**Comment by mchambaud** [comment]
Ohhhh this is awesome!!! Thanks @javoire

**Comment by javoire** [comment]
all cred to @Schubidu :)
