### ISSUE TITLE
How to specify folder for template module?

### ISSUE THREAD

**Issue by artemgrygor** [javoire/browserify-ng-html2js#35]
Hi,
looks like a very simple issue but have no idea how to do it correctly.
In the app there are _router.js_

` $routeProvider
        .when('/tutor/dashboard', {
            templateUrl: '/views/tutor/components/dashboard.html',
            controller: 'DashboardCtrl',
            controllerAs: 'vm'
        })`

which is located in one folder. And of course, the entry point main.js where I'm trying to require the template
`require('./views/tutor/components/dashboard/dashboard.html');`
or like this (which is an actual path)
`require('../../../views/tutor/components/dashboard/dashboard.html');`

Both of this give the error during browserify process that cannot find a module on the folder where the _router.js_ is located.
Any suggestions?

**Comment by javoire** [comment]
Hey! Sorry for late answer. Did you figure it out?

**Comment by artemgrygor** [comment]
@javoire no problem. Yes, it works. The issue could be closed now
